### ISSUE TITLE
Item to default context menu/-s

### ISSUE THREAD

**Issue by irvnriir** [LightAPIs/free-export-bookmarks#2]
Would be really great to make this extension add the export button to toolbar's and/or "Show All Bookmarks"/Library context menus . Like this https://addons.mozilla.org/en-US/firefox/addon/bookmark-tab-here/ does .

Without this, its unfortunately to long/slow to use .

**Comment by LightAPIs** [comment]
Well, i will take the time to figure out how to do that.

**Comment by LightAPIs** [comment]
This feature has been added to [v1.3.0](https://github.com/LightAPIs/free-export-bookmarks/releases/tag/v1.3.0).
