### ISSUE TITLE
Parent folder toggle activated results in export not being finished ever!

### ISSUE THREAD

**Issue by agizee** [LightAPIs/free-export-bookmarks#3]
![issue-never-ending-export-toggle-parent-folder](https://user-images.githubusercontent.com/9423559/140813207-a734f3a7-e330-43fd-8fca-f80a0ff953dc.png)
Hey thanks you so much for starting this.
I want to use that in my daily work with my Firefox [currently 94.0 - Release November 2, 2021]
But there (i have not tried the other ones) the export never completes if that
toggle is in active state. I am so keen on using the feature behind that toggle.
Please could you fix that?
![issue-never-ending-export-toggle-parent-folder-progress](https://user-images.githubusercontent.com/9423559/140815046-06a74f69-94b3-42f1-a7cd-2a9d1d2b4968.png)
Thanks

**Comment by LightAPIs** [comment]
Thank you for your feedback. It's really a mistake.

I have updated and fixed this error, you can go to [mozilla add-ons](https://addons.mozilla.org/zh-CN/firefox/addon/free-export-bookmarks/)  update to the new version to solve the problem.
