### ISSUE TITLE
Change the extension's name

### ISSUE THREAD

**Issue by soahyle** [LightAPIs/free-export-bookmarks#4]
Wonderful extension :heart: But the name is a little bit ambiguous :broken_heart: 

I think the word __"selective"__ like "Export Selective Bookmarks" (or something like that because [the name has been already  taken](https://chrome.google.com/webstore/detail/export-selective-bookmark/ahgbiciilcpclcekhegbhofljoolnfei)) instead of "free" is a clearer name which may help others finding out the extension easier.

Or you could rename to something that is less "general" and refactor the extension's overview section on Chrome or Firefox with more SEO related information. Like replace unnecessary description like _"Freely export the required bookmarks as HTML file"_, with something like __"Export selective bookmarks..."__.

**Comment by LightAPIs** [comment]
**"Selective Bookmarks Export Tool"**

What do you think about using that name?

**Comment by soahyle** [comment]
That's good bro, the extension will skyrocket to the moon soon :smile:

**Comment by LightAPIs** [comment]
Thank you for your suggestion, I have updated the extension's name. 😘
